# Generated by Django 5.1 on 2024-09-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo', models.CharField(max_length=50)),
                ('bebida', models.CharField(max_length=50)),
                ('postre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nacimiento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pais_origen',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='00000000-0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='ciudad',
            field=models.CharField(default='Sin ciudad', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='pais',
            field=models.CharField(default='Sin Pais', max_length=50),
            preserve_default=False,
        ),
    ]
